using static ReisProduction.Winhook.Utilities.Constants;
namespace ReisProduction.Winhook.Utilities;
public abstract record HookBase(bool ShouldStart = true);
public record ProcessStartHook(bool ShouldStart = true, params string[] ProcessNames) : HookBase(ShouldStart);
public record ProcessStopHook(bool ShouldStart = true, params string[] ProcessNames) : HookBase(ShouldStart);
public record ServiceStartHook(bool ShouldStart = true, params string[] ServiceNames) : HookBase(ShouldStart);
public record ServiceStopHook(bool ShouldStart = true, params string[] ServiceNames) : HookBase(ShouldStart);
public record ThreadStartHook(bool ShouldStart = true, params int[] ThreadIds) : HookBase(ShouldStart);
public record ThreadStopHook(bool ShouldStart = true, params int[] ThreadIds) : HookBase(ShouldStart);
public record ModuleLoadHook(bool ShouldStart = true, params string[] ModuleNames) : HookBase(ShouldStart);
public record ModuleUnloadHook(bool ShouldStart = true, params string[] ModuleNames) : HookBase(ShouldStart);
public record RegistryChangeHook(bool ShouldStart = true, params string[] RegistryPaths) : HookBase(ShouldStart);
public record SessionChangeHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record DeviceChangeHook(bool ShouldStart = true, params string[] DeviceIds) : HookBase(ShouldStart);
public record VolumeChangeHook(bool ShouldStart = true, params string[] DriveNames) : HookBase(ShouldStart);
public record PowerManagementHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record SystemConfigChangeHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record TimeChangeHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record SystemTraceHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record IP4RouteTableHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record IP6RouteTableHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record NetworkAdapterConfigChangeHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record ProcessTraceHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record ProcessStartTraceHook(bool ShouldStart = true, params string[] ProcessNames) : HookBase(ShouldStart);
public record ProcessStopTraceHook(bool ShouldStart = true, params string[] ProcessNames) : HookBase(ShouldStart);
public record ThreadTraceHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record ModuleTraceHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record BatchJobStartHook(bool ShouldStart = true, params string[] JobNames) : HookBase(ShouldStart);
public record BatchJobStopHook(bool ShouldStart = true, params string[] JobNames) : HookBase(ShouldStart);
public record ForegroundHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record MinimizeHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record SwitchHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record MoveSizeHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record MenuHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record MenuPopupHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record CaptureHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record ContextHelpHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record DragDropHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record DialogHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record ScrollingHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record DesktopSwitchHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record ConsoleHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record UiaHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record ObjectHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record KeyboardHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record MouseHook(bool ShouldStart = true) : HookBase(ShouldStart);
public record FileHook (bool ShouldStart = true, NotifyFilters Filters = AllNotifyFilters,
    bool IncludeCreated = true, bool IncludeChanged = true, bool IncludeDeleted = true,
    bool IncludeRenamed = true, bool IncludeError = true, params string[] Paths) : HookBase(ShouldStart);