namespace ReisProduction.Winhook.Utilities;
public abstract record HookBase(bool ShouldStart = true);
public record ProcessStartHook(params string[] ProcessNames) : HookBase;
public record ProcessStopHook(params string[] ProcessNames) : HookBase;
public record ServiceStartHook(params string[] ServiceNames) : HookBase;
public record ServiceStopHook(params string[] ServiceNames) : HookBase;
public record ThreadStartHook(params int[] ThreadIds) : HookBase;
public record ThreadStopHook(params int[] ThreadIds) : HookBase;
public record ModuleLoadHook(params string[] ModuleNames) : HookBase;
public record ModuleUnloadHook(params string[] ModuleNames) : HookBase;
public record SessionChangeHook() : HookBase;
public record DeviceChangeHook(params string[] DeviceIds) : HookBase;
public record VolumeChangeHook(params string[] DriveNames) : HookBase;
public record PowerManagementHook() : HookBase;
public record SystemConfigChangeHook() : HookBase;
public record TimeChangeHook() : HookBase;
public record SystemTraceHook() : HookBase;
public record IP4RouteTableHook() : HookBase;
public record IP6RouteTableHook() : HookBase;
public record NetworkAdapterConfigChangeHook() : HookBase;
public record ProcessTraceHook() : HookBase;
public record ProcessStartTraceHook(params string[] ProcessNames) : HookBase;
public record ProcessStopTraceHook(params string[] ProcessNames) : HookBase;
public record ThreadTraceHook() : HookBase;
public record ModuleTraceHook() : HookBase;
public record BatchJobStartHook(params string[] JobNames) : HookBase;
public record BatchJobStopHook(params string[] JobNames) : HookBase;
public record ForegroundHook() : HookBase;
public record MinimizeHook() : HookBase;
public record SwitchHook() : HookBase;
public record MoveSizeHook() : HookBase;
public record MenuHook() : HookBase;
public record MenuPopupHook() : HookBase;
public record CaptureHook() : HookBase;
public record ContextHelpHook() : HookBase;
public record DragDropHook() : HookBase;
public record DialogHook() : HookBase;
public record ScrollingHook() : HookBase;
public record DesktopSwitchHook() : HookBase;
public record ConsoleHook() : HookBase;
public record UiaHook() : HookBase;
public record ObjectHook() : HookBase;
public record KeyboardHook() : HookBase;
public record MouseHook() : HookBase;